// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPIoYcnOHR43bTNJJbB5NMoFWNtSVg7c',
    appId: '1:402387492032:web:1cc10b537983c0260ee125',
    messagingSenderId: '402387492032',
    projectId: 'icm-flutter-6822e',
    authDomain: 'icm-flutter-6822e.firebaseapp.com',
    storageBucket: 'icm-flutter-6822e.appspot.com',
    measurementId: 'G-D4574JNPQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7S0mNFnwdO8YIlRNXcTM10qsCDfiwpvY',
    appId: '1:402387492032:android:d0e5dbead499da720ee125',
    messagingSenderId: '402387492032',
    projectId: 'icm-flutter-6822e',
    storageBucket: 'icm-flutter-6822e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF88CmPPQZHJ4DAAbckYmgppQ1GjFlBcY',
    appId: '1:402387492032:ios:05110c74d52fcfe40ee125',
    messagingSenderId: '402387492032',
    projectId: 'icm-flutter-6822e',
    storageBucket: 'icm-flutter-6822e.appspot.com',
    iosClientId: '402387492032-imgvjhn93v32bifuj85r9etatb96oaps.apps.googleusercontent.com',
    iosBundleId: 'com.example.homework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF88CmPPQZHJ4DAAbckYmgppQ1GjFlBcY',
    appId: '1:402387492032:ios:05110c74d52fcfe40ee125',
    messagingSenderId: '402387492032',
    projectId: 'icm-flutter-6822e',
    storageBucket: 'icm-flutter-6822e.appspot.com',
    iosClientId: '402387492032-imgvjhn93v32bifuj85r9etatb96oaps.apps.googleusercontent.com',
    iosBundleId: 'com.example.homework',
  );
}
